apiVersion: gcp.managed.openshift.io/v1alpha1
kind: ProjectReference
metadata:
  name: example-clusternamespace-example-projectclaim
  namespace: gcp-project-operator
spec:
  # Add fields here
  gcpProjectID: example-GCPProjectID
  projectClaimCRLink: 
    name: example-projectclaim
    namespace: example-clusternamespace
  legalEntity:
    name: example-entity
    id: example-id
